In [55]:
import numpy as np 
print(np.__version__)

1.21.5


# for creating array

In [56]:
#we use numpy.array()
import numpy as np
l = [1,2,3,4,5,6,7,8,9]
cv = np.array(l,dtype=int )
print(cv)

[1 2 3 4 5 6 7 8 9]


In [57]:
import numpy as np
l = [1,2,3,4,5,6,7,8]
vb = np.array(l)
print(vb)
print(type(vb))
print(vb.ndim)#gives dimenstion of given array 

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
1


In [58]:
import numpy as np 
cv = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(cv)
print(cv.ndim)
print(cv.dtype)
print(cv.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
int32
(3, 4)


In [59]:
#creating array with random values 
import numpy as np 
fg = np.arange(1,10)
print(fg)

[1 2 3 4 5 6 7 8 9]


In [60]:
#cretaing array of all values are 0s with np.zeros()
#inside of paranthesis we write row and column values
import numpy as np 
df = np.zeros((2,3))
print(df)

[[0. 0. 0.]
 [0. 0. 0.]]


In [61]:
import numpy as np 
dg = np.ones((3,3))
print(dg)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [62]:
#for crating square matrix of identity matrix 
import numpy as np 
dg = np.eye(5)
print(dg)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# arithmetic with numpy

In [63]:
import numpy as np 
np1 = np.array([1,2,3,4,5,6])
np2 = np.array([7,8,9,10,11,12])
sum = np.add(np1,np2)
sub = np.subtract(np1,np2)
div = np.divide(np1,np2)
mul = np.multiply(np1,np2)


print("sum of thow array=",sum)
print("difference of two array = ",sub)
print("dividend of two array = ",div)
print("multiply of two array = ",mul)


sum of thow array= [ 8 10 12 14 16 18]
difference of two array =  [-6 -6 -6 -6 -6 -6]
dividend of two array =  [0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]
multiply of two array =  [ 7 16 27 40 55 72]


# Array Indexing

In [64]:
import numpy as np 
np1 = np.array([1,2,3,4,5,6])
print(np1[3])

4


In [65]:
import numpy as np 
npp = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(npp)
print(npp[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


# Array Slicing

In [66]:
#to extract first row of matrices
import numpy as np
my_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
sub_arr = my_a[0:1,:]
print(sub_arr)

[[1 2 3]]


In [67]:
#to import first column of matrices
import numpy as np 
my_b = np.array([[1,2,3],[4,5,6],[7,8,9]])
sub_arr2 = my_b[:,0:1]
print(sub_arr2)

[[1]
 [4]
 [7]]


# Boolean Indexing

In [68]:
import numpy as np 
x = np.arange(12).reshape(3,4)
print(x)
print("elements that greater than 5 = ",x[x>5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
elements that greater than 5 =  [ 6  7  8  9 10 11]


In [69]:
print("element less than 6 = ",x[x<6])

element less than 6 =  [0 1 2 3 4 5]


In [70]:
import numpy as np
v = np.array([4,7,8,3,4,78,45,34])
print(v[v==4])

[4 4]


In [71]:
print(v[v>=8])

[ 8 78 45 34]


In [72]:
print(v[v%2==0]) #sets having even number 

[ 4  8  4 78 34]


In [73]:
print(v[v%2!=0]) #sets of having odd number 

[ 7  3 45]


# Tranpose

In [75]:
import numpy as np 
x = np.arange(12).reshape(3,4)
print(x)
print("\n")
trans = x.T
print(trans)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Joing Array

In [96]:
#for this purpose we use numpy.concatenate()
import numpy as np 
nw = np.array([[1,2,3],[4,5,6]])
ne = np.array([[7,8,9],[10,11,12]])
print(nw ,"\n")
print(ne)
np.concatenate((nw,ne),axis=1)
#print(fd)

[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [94]:
#for this purpose we use numpy.concatenate()
import numpy as np 
nw = np.array([1,2,3])
ne = np.array([10,11,12])
print(nw ,"\n")
print(ne)
np.concatenate((nw,ne),axis =0)
#print(fd)

[1 2 3] 

[10 11 12]


array([ 1,  2,  3, 10, 11, 12])

# sorting

In [85]:
#ascending order 
a = np.array([32,4,8,11,20])
b = np.sort(a)
print(b)

[ 4  8 11 20 32]


In [84]:
#descending order
c = np.sort(a)[::-1]
print(c)

[32 20 11  8  4]


In [87]:
#argsort = gives index of sorted array
g = np.argsort(a)
print(g)

[1 2 3 4 0]


# split

In [91]:
import numpy as np 
x = np.arange(12).reshape(3,4)
print(x)
print("\n")
d,e = np.split(x,[2])
print(d)
print("\n")
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]]
