In [1]:
#to make simple object and class 
class student:  #class name declaration
    def setdata(self):  #method1
        self.name = input("enter name=")
        self.roll = int(input("enter roll number="))
        self.per = float(input("enter percentage="))
    def display(self):  #method 2
        print("name:",self.name)
        print("roll number:",self.roll)
        print("percentage:",self.per)
#object calling 
a=student()
a.setdata()
a.display()

enter name=rohit
enter roll number=3100012821043
enter percentage=78
name: rohit
roll number: 3100012821043
percentage: 78.0


In [5]:
#to make simple object and class with init function
#init function is a constructor which doesn't needs to call
class student:
    def __init__(self):
        self.name = input("enter name=")
        self.roll = int(input("enter roll number="))
        self.per = float(input("enter percentage="))
    def display(self):
        print("name:",self.name)
        print("roll number:",self.roll)
        print("percentage:",self.per)
a=student()
#a.setdata()
a.display()

enter name=evan
enter roll number=34
enter percentage=23
name: evan
roll number: 34
percentage: 23.0


In [2]:
#to make simple object and class with init function
#init function is a constructor which doesn't needs to call
#in this we initialize object parameterized
class student:
    def __init__(self,x,y,z):
        self.name = x
        self.roll = y
        self.per = z
        
    def display(self):
        print("name:",self.name)
        print("roll number:",self.roll)
        print("percentage:",self.per)
a=student("rohit",56,45)  #we initialize inside object declaration
#a.setdata()
a.display()

name: rohit
roll number: 56
percentage: 45


In [3]:
#class object constructor
#default constructor
class cons:
    def __init__(self):  
        self.x=2
        self.y=3
    def show(self):
        print(self.x)
        print(self.y)
a=cons()  #in this it is a empty parameter
a.show()

2
3


In [4]:
#class object constructor
#parameterized constructor
class cons:
    def __init__(self,a,b):
        self.x=a
        self.y=b
    def show(self):
        print(self.x)
        print(self.y)
a=cons(5,6)  #in this we object initialize in parameter
a.show()

5
6


In [5]:
#to make simple number program based on inheritance
class Num:
    a=10
    b=20
    def add(self):
        sum2 = self.a+self.b
        print("sum of the two number are=",sum2)
class num2(Num):
    c=40
    d=30
    def sub(self):
        diff = self.c - self.d
        print("subtraction of two number are = ",diff)

d=num2()
d.add()
d.sub()


sum of the two number are= 30
subtraction of two number are =  10


In [6]:
class car:
    def x1(self):
        print("this is baseclass")
class audi(car):
    def x2(self):
        print("this is child class")
        
f=audi()
f.x1()
f.x2()

this is baseclass
this is child class


In [6]:
#inheritance with constructor
class Person:
    def __init__(self,name,idnumber):
        self.name=name
        self.idnumber=idnumber
    def display(self):
        print("name=",self.name)
        print("id number=",self.idnumber)
        
class Employee(Person):
    def __init__(self,name,idnumber,salary,post):
        self.salary=salary
        self.post=post
        print("salary=",self.salary)
        print("post=",self.post)
        
        Person.__init__(self,name,idnumber)
        
d=Employee("Richard",88235,125000,"Technician")
d.display()

salary= 125000
post= Technician
name= Richard
id number= 88235


In [17]:
#multiple level inheritance 
class vehicle:
    def func1(self):
        print("this is parent class")
class car(vehicle):
    def func2(self):
        print("this is child class 1 i.e car")
        
class audi(vehicle):
    def func3(self):
        print("this is child class 2 i.e audi ")
        
f = car()
f1 = audi()
f.func1()
f.func2()
f1.func1()
f1.func3()
        

this is parent class
this is child class 1 i.e car
this is parent class
this is child class 2 i.e audi 


In [1]:
class stud:
    def __init__(self,name,id):
        self.name=name
        self.id=id
    def show(self):
        print("Name = ",self.name)
        print("Id no. = ",self.id)
d=stud("geetanshu","300012821055")
d.show()

Name =  geetanshu
Id no. =  300012821055


In [7]:
import numpy as np 
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([1,2,3,4,5],ndmin=3)
print(b)
print(np.multiply(a,b))
print(np.add(a,b))
print(np.subtract(a,b))

[[[1 2 3 4 5]]]
[[[ 1  4  9 16 25]
  [ 6 14 24 36 50]]]
[[[ 2  4  6  8 10]
  [ 7  9 11 13 15]]]
[[[0 0 0 0 0]
  [5 5 5 5 5]]]
